# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stepper.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):

    def __init__(self) -> None:
        self.sequence_text = ""
        self.sequences = None
        self.sequence_num = 0
        self.delay_text = ""

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(621, 691)
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(70, 40, 171, 581))
        self.textEdit.setObjectName("textEdit")
        self.textEdit.textChanged.connect(self.get_sequence)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(330, 140, 211, 81))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setCheckable(True)
        self.pushButton.toggle()
        self.pushButton.clicked.connect(self.apply_single)
        self.tableView = QtWidgets.QTableView(Form)
        self.tableView.setGeometry(QtCore.QRect(330, 250, 211, 371))
        self.tableView.setObjectName("tableView")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(370, 270, 131, 71))
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.toggle()
        self.pushButton_2.clicked.connect(self.run)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(350, 370, 181, 51))
        self.label.setObjectName("label")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(360, 490, 161, 91))
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.toggle()
        self.pushButton_3.clicked.connect(self.stop)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(400, 70, 81, 41))
        self.label_2.setObjectName("label_2")
        self.textEdit_2 = QtWidgets.QTextEdit(Form)
        self.textEdit_2.setGeometry(QtCore.QRect(390, 410, 104, 70))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_2.textChanged.connect(self.set_delay)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Stepper Motor -- [Preview]"))
        self.pushButton.setText(_translate("Form", "Apply Single Step"))
        self.pushButton_2.setText(_translate("Form", "RUN"))
        self.label.setText(_translate("Form", "Delay Between Steps (ms) "))
        self.pushButton_3.setText(_translate("Form", "STOP"))
        self.label_2.setText(_translate("Form", "SEQUENCE"))


    def apply_single(self):
        try:
            labelText = self.sequences[self.sequence_num]
            self.label_2.setText(labelText)
            self.sequence_num += 1

            if self.sequence_num == 12:
                self.sequence_num = 0
        except ValueError or TypeError or IndexError:
            print("Not an integer. Enter a sequence.")

    def run(self):
        print("run")

    def stop(self):
        print("stop")

    def get_sequence(self):
        self.sequence_text = self.textEdit.toPlainText()
        # val = 95
        if len(self.sequence_text) == 95:
            #self.sequences.append(self.sequence_text.splitlines())
            self.sequences = self.sequence_text.splitlines()
            self.textEdit.setReadOnly(True)

        return self.sequences    
    
    def set_delay(self):
        delay = ""
        self.delay_text = self.textEdit_2.toPlainText()
        if len(self.delay_text) == 2:
            print(self.delay_text, type(self.delay_text))
            self.delay_text = ""


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

